export const MAX_PARTICLES = 5000

export const PARTICLE_CONVECTION_COEFFICIENT = 0.04

export const PARTICLE_CONDUCTION_COEFFICIENT = 0.5

export const PARTICLE_COLLISION_RADIUS = 0.06

export const PARTICLE_VISIBLE_RADIUS = 15

export const LAMP_TEMPERATURE = 100

export const PARTICLE_MAX_VERTICAL_SPEED = 0.01

export const PARTICLE_MAX_HORIZONTAL_SPEED = 0.001

export const GRAVITY = -0.0001
