import { WorkItem } from './types'

export const MY_WORK: Record<string, WorkItem[]> = {
  'Work Experience': [
    {
      header: 'Agricultural Finance Lender',
      image: '/react-icon.svg',
      description:
        'As a senior consultant at Headstorm on an agricultural finance client, I served as a UI SME to completely rebuild an internal loan management tool. I helped architect a new React/.NET Core solution for the loan management portal, building all components from scratch and creating a blazingly fast, fully-customized, and live-collaborative tool. In this role I also maintained an internal legacy Angular/.NET application, a customer-facing Next.js/Node.js microservices application, and a few other smaller sites for third-party use.',
      tags: [
        'TypeScript',
        'React',
        'CSS',
        'Styled Components',
        'Vite',
        'Orval',
        '.NET',
        '.NET Core',
        'Node.js',
        'Next.js',
      ],
    },
    {
      header: 'Fortune 500 Retail Company',
      image: '/terraform-icon.svg',
      description:
        "As a consultant at Headstorm on a Fortune 500 retail client, I led an overhaul of their cloud deployment strategy. Created a unified ARM Template deployment solution, resolving conflicts between the company's devops and developer teams, who used Terraform and ARM templates respectively. The solution was a stop-gap fix until Terraform fully supported the Logic Apps that the developers were building.",
      tags: ['Cloud', 'Azure', 'Terraform', 'ARM Templates', 'DevOps'],
    },
  ],
  Certifications: [
    {
      header: 'AZ-900 - Azure Fundamentals',
      image: '/AZ900.svg',
      description:
        'Earners of the Azure Fundamentals certification have demonstrated foundational level knowledge of cloud services and how those services are provided with Microsoft Azure.',
      tags: ['Cloud', 'Azure', 'Security', 'Virtualization', 'Cloud Data'],
      href: 'https://www.credly.com/badges/ff554b6a-5cb2-433a-af7e-1345ea8b7a51/public_url',
    },
    {
      header: 'AZ-204 - Azure Developer Associate',
      image: '/AZ204.svg',
      description:
        'Earning Azure Developer Associate certification validates the skills and knowledge to design, build, test, and maintain cloud applications and services on Microsoft Azure. Candidates participate in all phases of cloud development from requirements definition and design, to development, deployment, and maintenance.',
      tags: ['Cloud', 'Azure', 'Security', 'Virtualization', 'Cloud Data', 'Architecture'],
      href: 'https://www.credly.com/badges/36e250d4-692c-4198-bcd6-4df6be171d32/public_url',
    },
  ],
  'Github Contributions': [
    {
      header: 'Too Many Hooks',
      image: '/too-many-hooks-small-white.png',
      description:
        'I co-created and maintain this open-source React library of opinionated hooks with full TypeScript support. too-many-hooks seeks to provide reusable and dev-friendly hooks for as many use-cases as possible.',
      tags: ['TypeScript', 'React', 'Hooks', 'Open Source'],
      href: 'https://github.com/yobgob/too-many-hooks',
    },
    {
      header: 'Logseq Plugin: Colored Threads',
      image: '/logseq-plugin-colored-threads.svg',
      description:
        'I created a plugin for Logseq to meet a personal desire of having my indentation be colored according to indent level, inspired by my VSCode editor. The open-source plugin is now listed on the Logseq plugin marketplace.',
      tags: ['TypeScript', 'Open Source', 'Logseq', 'Plugin'],
      href: 'https://github.com/patrickdevries/logseq-plugin-colored-threads',
    },
    {
      header: 'Foundry UI',
      image: '/Foundry-BG.png',
      description:
        'An open-source React library of reusable styled components. I have contributed additions to the provider and multiple components. This library is also what I used to build the original version of this website.',
      tags: ['TypeScript', 'React', 'CSS', 'Styled Components', 'Open Source'],
      href: 'https://github.com/Headstorm/foundry-ui/pulls?q=is%3Apr+author%3APatrickDeVries',
    },
    {
      header: 'Joker Cord',
      image: '/pokeball.svg',
      description:
        'A Discord self-bot that I revived for personal use. It automates the identification and capture of pokemon generated by a separate Discord bot game. Images are captured and hashed, names are solved using hints and regular expressions, and it can automatically send capture commands or put them in your clipboard.',
      tags: ['Python', 'Discord Bot', 'Image Matching', 'Open Source', 'ToS Violation'],
      href: 'https://github.com/PatrickDeVries/JokerCord',
    },
  ],
  'Live Sites I Helped Design/Build': [
    {
      header: 'XDO Maturity Quiz',
      image: '/xdo.svg',
      description: `A Buzzfeed style quiz for taking a quick assessment of a company's maturity in key categories. Used as a Marketing tool for Headstorm to introduce potential clients to XDO offerings in a fun and interactive package.`,
      tags: ['Typescript', 'React', 'Foundry UI', 'UX Design', 'Marketing'],
      href: 'https://xdocicdapp.azurewebsites.net/',
    },
    {
      header: 'Idle Content',
      image: '/idleContent.gif',
      description: `A gallery website to display my creative computing class' projects. Worked with the class to design and implement the site. Site is built out of flexible JS modules of a few types to be able to accommodate several kinds of media according to what each student made.`,
      tags: ['JavaScript', 'CSS', 'Creative Computing', 'Gallery'],
      href: 'https://www.melanieclemmons.com/HYBRID/',
    },
  ],
  'Art Projects': [
    {
      header: 'Three Web Stalker',
      image: '/3ws.png',
      description:
        'A chrome extension I developed as an art project exploring alternatives to modern browsers. The work is inspired by The Web Stalker and adjusted for modern web with ThreeJS. Entering a search term or a link generated an explorable and interactible 3D graph of websites that can be navigated through.',
      tags: ['ThreeJS', 'JavaScript', 'CSS', 'Extension', 'Web Crawler', 'Creative Computing'],
      href: 'https://chrome.google.com/webstore/detail/three-web-stalker/klmhhglpadcjglppjmjpepicoidecdlo',
    },
    {
      header: 'Lasers',
      image: '/lasers.png',
      description:
        'My first project working in ThreeJS. A site where you can create and explore a unique set of lasers with simple click-and-drag.',
      tags: ['ThreeJS', 'JavaScript', 'CSS', 'Creative Computing'],
    },
  ],
  Random: [
    {
      header: 'Solids vs Stripes vs Even vs Odds',
      image: '/8ball.png',
      description:
        'A tool for tracking the rules and game state of the 4-player pool game, solids vs stripes vs evens vs odds. Players enter nicknames, then as they sink balls they input them. The resulting role assignments are visualized in the graph.',
      tags: ['TypeScript', 'CSS', 'Pool', 'Game'],
      to: '/portfolio/sseo',
    },
  ],
}
